// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=[you,me]"` // parameters are auto validated
}

type Response struct {
	Message  string `json :"message"` // response is auto validated
	Message1 string `json:"message1"` // response is auto validated
}
