// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	greet "greet/api/internal/handler/greet"
	"greet/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SvcGvcMiddleware, serverCtx.JwtMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/greet/from/:name",
					Handler: greet.GreetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
