// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: add.proto

package server

import (
	"context"

	"greet/service/add/internal/logic"
	"greet/service/add/internal/svc"
	"greet/service/add/pb/add"
)

type AdderServer struct {
	svcCtx *svc.ServiceContext
	add.UnimplementedAdderServer
}

func NewAdderServer(svcCtx *svc.ServiceContext) *AdderServer {
	return &AdderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdderServer) Add(ctx context.Context, in *add.AddReq) (*add.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
