// Code generated by "stringer -type=ErrCode -linecomment -output strings.go"; DO NOT EDIT.

package xerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrCodeNone-0]
	_ = x[ErrCodeServerError-500]
	_ = x[ErrCodeUnknown-10000]
	_ = x[ErrCodeParamsInvalid-10001]
	_ = x[ErrCodeTokenInvalid-10002]
	_ = x[ErrCodeAuthFailed-10003]
}

const (
	_ErrCode_name_0 = "OK"
	_ErrCode_name_1 = "服务异常"
	_ErrCode_name_2 = "未知错误参数错误Token 无效认证失败"
)

var (
	_ErrCode_index_2 = [...]uint8{0, 12, 24, 36, 48}
)

func (i ErrCode) String() string {
	switch {
	case i == 0:
		return _ErrCode_name_0
	case i == 500:
		return _ErrCode_name_1
	case 10000 <= i && i <= 10003:
		i -= 10000
		return _ErrCode_name_2[_ErrCode_index_2[i]:_ErrCode_index_2[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
